AWSTemplateFormatVersion: 2010-09-09
Description: ND9991 C3 L4
Resources:

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH via Port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
        - !Ref  InstanceSecurityGroup
      KeyName: Abbas3
      ImageId: ami-052efd3df9dad4825
      InstanceType: t2.micro


